# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow_burn(object):
    def setupUi(self, MainWindow_burn):
        MainWindow_burn.setObjectName(_fromUtf8("MainWindow_burn"))
        MainWindow_burn.resize(718, 552)
        self.centralwidget = QtGui.QWidget(MainWindow_burn)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 701, 491))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 651, 421))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_offboard = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_offboard.setObjectName(_fromUtf8("pushButton_offboard"))
        self.horizontalLayout.addWidget(self.pushButton_offboard)
        self.pushButton_takeoff = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_takeoff.setObjectName(_fromUtf8("pushButton_takeoff"))
        self.horizontalLayout.addWidget(self.pushButton_takeoff)
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_4 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit = QtGui.QTextEdit(self.layoutWidget)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pushButton_offboard_2 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_offboard_2.setObjectName(_fromUtf8("pushButton_offboard_2"))
        self.horizontalLayout_2.addWidget(self.pushButton_offboard_2)
        self.bsp_dir_lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.bsp_dir_lineEdit.setObjectName(_fromUtf8("bsp_dir_lineEdit"))
        self.horizontalLayout_2.addWidget(self.bsp_dir_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_offboard_4 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_offboard_4.setObjectName(_fromUtf8("pushButton_offboard_4"))
        self.horizontalLayout_3.addWidget(self.pushButton_offboard_4)
        self.app_dir_lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.app_dir_lineEdit.setObjectName(_fromUtf8("app_dir_lineEdit"))
        self.horizontalLayout_3.addWidget(self.app_dir_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pushButton_offboard_5 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_offboard_5.setObjectName(_fromUtf8("pushButton_offboard_5"))
        self.horizontalLayout_4.addWidget(self.pushButton_offboard_5)
        self.log_dir_lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.log_dir_lineEdit.setObjectName(_fromUtf8("log_dir_lineEdit"))
        self.horizontalLayout_4.addWidget(self.log_dir_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pushButton_offboard_6 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_offboard_6.setObjectName(_fromUtf8("pushButton_offboard_6"))
        self.horizontalLayout_5.addWidget(self.pushButton_offboard_6)
        self.param_dir_lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.param_dir_lineEdit.setObjectName(_fromUtf8("param_dir_lineEdit"))
        self.horizontalLayout_5.addWidget(self.param_dir_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.frame = QtGui.QFrame(self.tab_2)
        self.frame.setGeometry(QtCore.QRect(90, 170, 521, 321))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 10, 551, 152))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.radioButton_dis = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButton_dis.setObjectName(_fromUtf8("radioButton_dis"))
        self.verticalLayout_4.addWidget(self.radioButton_dis)
        self.radioButton_svo_x = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButton_svo_x.setObjectName(_fromUtf8("radioButton_svo_x"))
        self.verticalLayout_4.addWidget(self.radioButton_svo_x)
        self.radioButton_svo_y = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButton_svo_y.setObjectName(_fromUtf8("radioButton_svo_y"))
        self.verticalLayout_4.addWidget(self.radioButton_svo_y)
        self.radioButton_tmp = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButton_tmp.setObjectName(_fromUtf8("radioButton_tmp"))
        self.verticalLayout_4.addWidget(self.radioButton_tmp)
        self.radioButton_roll = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButton_roll.setObjectName(_fromUtf8("radioButton_roll"))
        self.verticalLayout_4.addWidget(self.radioButton_roll)
        self.radioButton_pitch = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButton_pitch.setObjectName(_fromUtf8("radioButton_pitch"))
        self.verticalLayout_4.addWidget(self.radioButton_pitch)
        self.radioButton_yaw = QtGui.QRadioButton(self.layoutWidget1)
        self.radioButton_yaw.setObjectName(_fromUtf8("radioButton_yaw"))
        self.verticalLayout_4.addWidget(self.radioButton_yaw)
        self.horizontalLayout_13.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_dis = QtGui.QLabel(self.layoutWidget1)
        self.label_dis.setObjectName(_fromUtf8("label_dis"))
        self.verticalLayout_5.addWidget(self.label_dis)
        self.label_svo_x = QtGui.QLabel(self.layoutWidget1)
        self.label_svo_x.setObjectName(_fromUtf8("label_svo_x"))
        self.verticalLayout_5.addWidget(self.label_svo_x)
        self.label_svo_y = QtGui.QLabel(self.layoutWidget1)
        self.label_svo_y.setObjectName(_fromUtf8("label_svo_y"))
        self.verticalLayout_5.addWidget(self.label_svo_y)
        self.label_tmp = QtGui.QLabel(self.layoutWidget1)
        self.label_tmp.setObjectName(_fromUtf8("label_tmp"))
        self.verticalLayout_5.addWidget(self.label_tmp)
        self.label_roll = QtGui.QLabel(self.layoutWidget1)
        self.label_roll.setObjectName(_fromUtf8("label_roll"))
        self.verticalLayout_5.addWidget(self.label_roll)
        self.label_pitch = QtGui.QLabel(self.layoutWidget1)
        self.label_pitch.setObjectName(_fromUtf8("label_pitch"))
        self.verticalLayout_5.addWidget(self.label_pitch)
        self.label_yaw = QtGui.QLabel(self.layoutWidget1)
        self.label_yaw.setObjectName(_fromUtf8("label_yaw"))
        self.verticalLayout_5.addWidget(self.label_yaw)
        self.horizontalLayout_13.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(70, 20, 551, 240))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.radioButton_xacc = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_xacc.setObjectName(_fromUtf8("radioButton_xacc"))
        self.verticalLayout_6.addWidget(self.radioButton_xacc)
        self.radioButton_yacc = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_yacc.setObjectName(_fromUtf8("radioButton_yacc"))
        self.verticalLayout_6.addWidget(self.radioButton_yacc)
        self.radioButton_zacc = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_zacc.setObjectName(_fromUtf8("radioButton_zacc"))
        self.verticalLayout_6.addWidget(self.radioButton_zacc)
        self.radioButton_xgyro = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_xgyro.setObjectName(_fromUtf8("radioButton_xgyro"))
        self.verticalLayout_6.addWidget(self.radioButton_xgyro)
        self.radioButton_ygyro = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_ygyro.setObjectName(_fromUtf8("radioButton_ygyro"))
        self.verticalLayout_6.addWidget(self.radioButton_ygyro)
        self.radioButton_zgyro = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_zgyro.setObjectName(_fromUtf8("radioButton_zgyro"))
        self.verticalLayout_6.addWidget(self.radioButton_zgyro)
        self.radioButton_xmag = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_xmag.setObjectName(_fromUtf8("radioButton_xmag"))
        self.verticalLayout_6.addWidget(self.radioButton_xmag)
        self.radioButton_ymag = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_ymag.setObjectName(_fromUtf8("radioButton_ymag"))
        self.verticalLayout_6.addWidget(self.radioButton_ymag)
        self.radioButton_zmag = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_zmag.setObjectName(_fromUtf8("radioButton_zmag"))
        self.verticalLayout_6.addWidget(self.radioButton_zmag)
        self.radioButton_distance = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_distance.setObjectName(_fromUtf8("radioButton_distance"))
        self.verticalLayout_6.addWidget(self.radioButton_distance)
        self.radioButton_pressure = QtGui.QRadioButton(self.layoutWidget_2)
        self.radioButton_pressure.setObjectName(_fromUtf8("radioButton_pressure"))
        self.verticalLayout_6.addWidget(self.radioButton_pressure)
        self.horizontalLayout_14.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_xacc = QtGui.QLabel(self.layoutWidget_2)
        self.label_xacc.setObjectName(_fromUtf8("label_xacc"))
        self.verticalLayout_7.addWidget(self.label_xacc)
        self.label_yacc = QtGui.QLabel(self.layoutWidget_2)
        self.label_yacc.setObjectName(_fromUtf8("label_yacc"))
        self.verticalLayout_7.addWidget(self.label_yacc)
        self.label_zacc = QtGui.QLabel(self.layoutWidget_2)
        self.label_zacc.setObjectName(_fromUtf8("label_zacc"))
        self.verticalLayout_7.addWidget(self.label_zacc)
        self.label_xgyro = QtGui.QLabel(self.layoutWidget_2)
        self.label_xgyro.setObjectName(_fromUtf8("label_xgyro"))
        self.verticalLayout_7.addWidget(self.label_xgyro)
        self.label_ygyro = QtGui.QLabel(self.layoutWidget_2)
        self.label_ygyro.setObjectName(_fromUtf8("label_ygyro"))
        self.verticalLayout_7.addWidget(self.label_ygyro)
        self.label_zgyro = QtGui.QLabel(self.layoutWidget_2)
        self.label_zgyro.setObjectName(_fromUtf8("label_zgyro"))
        self.verticalLayout_7.addWidget(self.label_zgyro)
        self.label_xmag = QtGui.QLabel(self.layoutWidget_2)
        self.label_xmag.setObjectName(_fromUtf8("label_xmag"))
        self.verticalLayout_7.addWidget(self.label_xmag)
        self.label_ymag = QtGui.QLabel(self.layoutWidget_2)
        self.label_ymag.setObjectName(_fromUtf8("label_ymag"))
        self.verticalLayout_7.addWidget(self.label_ymag)
        self.label_zmag = QtGui.QLabel(self.layoutWidget_2)
        self.label_zmag.setObjectName(_fromUtf8("label_zmag"))
        self.verticalLayout_7.addWidget(self.label_zmag)
        self.label_distance = QtGui.QLabel(self.layoutWidget_2)
        self.label_distance.setObjectName(_fromUtf8("label_distance"))
        self.verticalLayout_7.addWidget(self.label_distance)
        self.label_pressure = QtGui.QLabel(self.layoutWidget_2)
        self.label_pressure.setObjectName(_fromUtf8("label_pressure"))
        self.verticalLayout_7.addWidget(self.label_pressure)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        self.pushButton_imutest = QtGui.QPushButton(self.tab_3)
        self.pushButton_imutest.setGeometry(QtCore.QRect(80, 280, 75, 23))
        self.pushButton_imutest.setObjectName(_fromUtf8("pushButton_imutest"))
        self.pushButton_esctest = QtGui.QPushButton(self.tab_3)
        self.pushButton_esctest.setGeometry(QtCore.QRect(80, 330, 75, 23))
        self.pushButton_esctest.setObjectName(_fromUtf8("pushButton_esctest"))
        self.label_imutest = QtGui.QLabel(self.tab_3)
        self.label_imutest.setGeometry(QtCore.QRect(210, 290, 54, 12))
        self.label_imutest.setObjectName(_fromUtf8("label_imutest"))
        self.label_esctest = QtGui.QLabel(self.tab_3)
        self.label_esctest.setGeometry(QtCore.QRect(210, 330, 54, 12))
        self.label_esctest.setObjectName(_fromUtf8("label_esctest"))
        self.pushButton_esctest_2 = QtGui.QPushButton(self.tab_3)
        self.pushButton_esctest_2.setGeometry(QtCore.QRect(80, 380, 75, 23))
        self.pushButton_esctest_2.setObjectName(_fromUtf8("pushButton_esctest_2"))
        self.label_esctest_2 = QtGui.QLabel(self.tab_3)
        self.label_esctest_2.setGeometry(QtCore.QRect(210, 380, 54, 12))
        self.label_esctest_2.setObjectName(_fromUtf8("label_esctest_2"))
        self.label_distest = QtGui.QLabel(self.tab_3)
        self.label_distest.setGeometry(QtCore.QRect(300, 290, 54, 12))
        self.label_distest.setObjectName(_fromUtf8("label_distest"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.frame_3 = QtGui.QFrame(self.tab_10)
        self.frame_3.setGeometry(QtCore.QRect(30, 110, 651, 361))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.pushButton_connect = QtGui.QPushButton(self.tab_10)
        self.pushButton_connect.setGeometry(QtCore.QRect(384, 39, 75, 23))
        self.pushButton_connect.setObjectName(_fromUtf8("pushButton_connect"))
        self.lineEdit_ip = QtGui.QLineEdit(self.tab_10)
        self.lineEdit_ip.setGeometry(QtCore.QRect(71, 40, 291, 20))
        self.lineEdit_ip.setObjectName(_fromUtf8("lineEdit_ip"))
        self.pushButton_disconnect = QtGui.QPushButton(self.tab_10)
        self.pushButton_disconnect.setGeometry(QtCore.QRect(465, 39, 75, 23))
        self.pushButton_disconnect.setObjectName(_fromUtf8("pushButton_disconnect"))
        self.tabWidget.addTab(self.tab_10, _fromUtf8(""))
        MainWindow_burn.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow_burn)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 718, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow_burn.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow_burn)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow_burn.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_burn)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.wifi)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.versions)
        QtCore.QObject.connect(self.pushButton_3, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.app_version)
        QtCore.QObject.connect(self.pushButton_offboard_4, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.app_click)
        QtCore.QObject.connect(self.pushButton_offboard_5, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.log_click)
        QtCore.QObject.connect(self.pushButton_offboard, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.bsp)
        QtCore.QObject.connect(self.pushButton_offboard_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.bsp_click)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.check_log)
        QtCore.QObject.connect(self.pushButton_takeoff, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.airbee)
        QtCore.QObject.connect(self.radioButton_dis, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.on_radioButton_clicked)
        QtCore.QObject.connect(self.radioButton_svo_x, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.on_radioButton_clicked)
        QtCore.QObject.connect(self.radioButton_svo_y, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.on_radioButton_clicked)
        QtCore.QObject.connect(self.radioButton_tmp, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.on_radioButton_clicked)
        QtCore.QObject.connect(self.radioButton_roll, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.on_radioButton_clicked)
        QtCore.QObject.connect(self.radioButton_pitch, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.on_radioButton_clicked)
        QtCore.QObject.connect(self.radioButton_yaw, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.on_radioButton_clicked)
        QtCore.QObject.connect(self.pushButton_offboard_6, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.param_click)
        QtCore.QObject.connect(self.pushButton_disconnect, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.disconnect)
        QtCore.QObject.connect(self.pushButton_connect, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.connect)
        QtCore.QObject.connect(self.pushButton_imutest, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.imu_test)
        QtCore.QObject.connect(self.pushButton_esctest, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.ESC_test)
        QtCore.QObject.connect(self.pushButton_esctest_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow_burn.boot_time)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_burn)

    def retranslateUi(self, MainWindow_burn):
        MainWindow_burn.setWindowTitle(_translate("MainWindow_burn", "MainWindow", None))
        self.pushButton_offboard.setText(_translate("MainWindow_burn", "烧写BSP", None))
        self.pushButton_takeoff.setText(_translate("MainWindow_burn", "烧写APP", None))
        self.pushButton.setText(_translate("MainWindow_burn", "bsp版本", None))
        self.pushButton_3.setText(_translate("MainWindow_burn", "app版本", None))
        self.pushButton_2.setText(_translate("MainWindow_burn", "显示wifi", None))
        self.pushButton_4.setText(_translate("MainWindow_burn", "显示log", None))
        self.pushButton_5.setText(_translate("MainWindow_burn", "烧写param", None))
        self.pushButton_offboard_2.setText(_translate("MainWindow_burn", "BSP文件", None))
        self.pushButton_offboard_4.setText(_translate("MainWindow_burn", "app文件", None))
        self.pushButton_offboard_5.setText(_translate("MainWindow_burn", "log文件", None))
        self.pushButton_offboard_6.setText(_translate("MainWindow_burn", "param文件", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow_burn", "burn tool", None))
        self.radioButton_dis.setText(_translate("MainWindow_burn", "current_distance", None))
        self.radioButton_svo_x.setText(_translate("MainWindow_burn", "svo x", None))
        self.radioButton_svo_y.setText(_translate("MainWindow_burn", "svo y", None))
        self.radioButton_tmp.setText(_translate("MainWindow_burn", "temprature", None))
        self.radioButton_roll.setText(_translate("MainWindow_burn", "roll", None))
        self.radioButton_pitch.setText(_translate("MainWindow_burn", "pitch", None))
        self.radioButton_yaw.setText(_translate("MainWindow_burn", "yaw", None))
        self.label_dis.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_svo_x.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_svo_y.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_tmp.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_roll.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_pitch.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_yaw.setText(_translate("MainWindow_burn", "- - -", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow_burn", "QGC tool", None))
        self.radioButton_xacc.setText(_translate("MainWindow_burn", "xacc", None))
        self.radioButton_yacc.setText(_translate("MainWindow_burn", "yacc", None))
        self.radioButton_zacc.setText(_translate("MainWindow_burn", "zacc", None))
        self.radioButton_xgyro.setText(_translate("MainWindow_burn", "xgyro", None))
        self.radioButton_ygyro.setText(_translate("MainWindow_burn", "ygyro", None))
        self.radioButton_zgyro.setText(_translate("MainWindow_burn", "zgyro", None))
        self.radioButton_xmag.setText(_translate("MainWindow_burn", "xmag", None))
        self.radioButton_ymag.setText(_translate("MainWindow_burn", "ymag", None))
        self.radioButton_zmag.setText(_translate("MainWindow_burn", "zmag", None))
        self.radioButton_distance.setText(_translate("MainWindow_burn", "distance", None))
        self.radioButton_pressure.setText(_translate("MainWindow_burn", "pressure", None))
        self.label_xacc.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_yacc.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_zacc.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_xgyro.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_ygyro.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_zgyro.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_xmag.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_ymag.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_zmag.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_distance.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_pressure.setText(_translate("MainWindow_burn", "- - -", None))
        self.pushButton_imutest.setText(_translate("MainWindow_burn", "imu test", None))
        self.pushButton_esctest.setText(_translate("MainWindow_burn", "ESC test", None))
        self.label_imutest.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_esctest.setText(_translate("MainWindow_burn", "- - -", None))
        self.pushButton_esctest_2.setText(_translate("MainWindow_burn", "boot test", None))
        self.label_esctest_2.setText(_translate("MainWindow_burn", "- - -", None))
        self.label_distest.setText(_translate("MainWindow_burn", "- - -", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow_burn", "Hardware_test", None))
        self.pushButton_connect.setText(_translate("MainWindow_burn", "connect", None))
        self.pushButton_disconnect.setText(_translate("MainWindow_burn", "disconnect", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow_burn", "Page", None))

